import os
import json
from datetime import datetime
from typing import Dict, List, Any


class ScriptExporter:
    """Generates batch/PowerShell scripts and JSON manifests from action history."""

    def __init__(self, actions: List[dict], base_path: str, working_directory: str = ""):
        self.actions = [a for a in actions if not a.get("reverted")]
        self.base_path = base_path
        self.working_directory = working_directory

    def _rebase_path(self, path: str) -> str:
        """Replace the working directory prefix with base_path."""
        if not path or not self.working_directory:
            return path
        # Normalize separators
        norm_path = path.replace("/", os.sep).replace("\\", os.sep)
        norm_wd = self.working_directory.replace("/", os.sep).replace("\\", os.sep)
        if norm_path.startswith(norm_wd):
            relative = norm_path[len(norm_wd):].lstrip(os.sep)
            return os.path.join(self.base_path, relative)
        return path

    def generate_batch(self) -> str:
        """Generate a Windows batch (.bat) script."""
        lines = [
            "@echo off",
            "REM Generated by FileFlow AI",
            f"REM Base path: {self.base_path}",
            f"REM Generated at: {datetime.now().isoformat()}",
            "",
        ]
        for action in self.actions:
            line = self._action_to_batch(action)
            if line:
                lines.append(line)
        lines.append("")
        lines.append("echo Done.")
        lines.append("pause")
        return "\n".join(lines)

    def generate_powershell(self) -> str:
        """Generate a PowerShell (.ps1) script."""
        lines = [
            "# Generated by FileFlow AI",
            f"# Base path: {self.base_path}",
            f"# Generated at: {datetime.now().isoformat()}",
            "",
        ]
        for action in self.actions:
            line = self._action_to_powershell(action)
            if line:
                lines.append(line)
        lines.append("")
        lines.append('Write-Host "Done."')
        return "\n".join(lines)

    def generate_manifest(
        self,
        file_metadata: Dict[str, dict],
        categories: Dict[str, list],
    ) -> dict:
        """Generate a JSON manifest."""
        return {
            "generated_at": datetime.now().isoformat(),
            "base_path": self.base_path,
            "actions": self.actions,
            "file_metadata": file_metadata,
            "categories": categories,
            "summary": {
                "total_actions": len(self.actions),
                "files_moved": len([a for a in self.actions if "move" in a.get("action_type", "")]),
                "files_created": len([a for a in self.actions if "create" in a.get("action_type", "")]),
                "files_deleted": len([a for a in self.actions if "delete" in a.get("action_type", "")]),
                "files_renamed": len([a for a in self.actions if "rename" in a.get("action_type", "")]),
            },
        }

    def _action_to_batch(self, action: dict) -> str:
        atype = action.get("action_type", "")
        source = self._rebase_path(action.get("source_path", ""))
        target = self._rebase_path(action.get("target_path", ""))
        item_name = action.get("item_name", "")
        new_name = action.get("new_name", "")

        if atype in ("move_file", "move_folder"):
            return f'move "{source}" "{target}"'
        elif atype in ("rename_file", "rename_folder"):
            return f'ren "{source}" "{new_name}"'
        elif atype == "create_folder":
            path = os.path.join(target, item_name) if target else item_name
            return f'mkdir "{self._rebase_path(path)}"'
        elif atype == "create_file":
            path = os.path.join(target, item_name) if target else item_name
            return f'type nul > "{self._rebase_path(path)}"'
        elif atype == "delete_file":
            return f'del "{source}"'
        elif atype == "delete_folder":
            return f'rmdir /s /q "{source}"'
        elif atype == "modify_file":
            return f'REM Modified: {source}'
        return f"REM Unsupported action: {atype}"

    def _action_to_powershell(self, action: dict) -> str:
        atype = action.get("action_type", "")
        source = self._rebase_path(action.get("source_path", ""))
        target = self._rebase_path(action.get("target_path", ""))
        item_name = action.get("item_name", "")
        new_name = action.get("new_name", "")

        if atype in ("move_file", "move_folder"):
            return f'Move-Item -Path "{source}" -Destination "{target}"'
        elif atype in ("rename_file", "rename_folder"):
            return f'Rename-Item -Path "{source}" -NewName "{new_name}"'
        elif atype == "create_folder":
            path = os.path.join(target, item_name) if target else item_name
            return f'New-Item -ItemType Directory -Path "{self._rebase_path(path)}" -Force'
        elif atype == "create_file":
            path = os.path.join(target, item_name) if target else item_name
            return f'New-Item -ItemType File -Path "{self._rebase_path(path)}" -Force'
        elif atype == "delete_file":
            return f'Remove-Item -Path "{source}" -Force'
        elif atype == "delete_folder":
            return f'Remove-Item -Path "{source}" -Recurse -Force'
        elif atype == "modify_file":
            return f'# Modified: {source}'
        return f"# Unsupported action: {atype}"
